version: "3"

services:
  postgres:
    container_name: postgres_2
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - postgres

networks:
  postgres:
    driver: bridge